import type { Metadata } from "next";

/**
 * Single source of truth for site-wide brand, routing and metadata.
 *
 * Every consumer (root layout, sitemap.ts, robots.ts, manifest.ts, JSON-LD
 * blocks, per-page `metadata` exports) reads from here so titles, canonicals
 * and the sitemap can never drift apart.
 *
 * Safe to import from both server and client components.
 */

/**
 * Public origin, used for every absolute URL the site emits.
 *
 * `NEXT_PUBLIC_SITE_URL` wins when it is set, which is what you want for a
 * preview or custom domain. The fallback is the live production host rather
 * than localhost on purpose: if the variable is ever missing, a localhost
 * fallback ships a site whose canonical, og:url, robots.txt and sitemap all
 * point at http://localhost:3000, which tells search engines to ignore the
 * whole domain. Failing to the real host is far safer than failing to localhost.
 */
const PRODUCTION_SITE_URL = "https://vedik-demo.netlify.app";

const RAW_SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.trim() || PRODUCTION_SITE_URL;

/** Origin + optional basePath, normalised without a trailing slash. */
export const SITE_URL = RAW_SITE_URL.replace(/\/+$/, "");

/** True when no env override is in play, i.e. URLs point at production. */
export const USING_DEFAULT_SITE_URL = !process.env.NEXT_PUBLIC_SITE_URL?.trim();

export const SITE = {
  name: "VEDIK School ERP",
  shortName: "VEDIK",
  legalName: "VEDIK School Management ERP",
  tagline: "The complete school management system",
  description:
    "VEDIK School ERP is an all-in-one school management system for Indian schools. Manage admissions, attendance, exams, fees, payroll, library, transport, hostel and reports from a single dashboard.",
  applicationCategory: "BusinessApplication",
  locale: "en_IN",
  lang: "en-IN",
  version: "2.5",
  contactEmail: "digi.tracks@outlook.com",
  organization: "Digitracks",
  priceCurrency: "INR",
} as const;

export const SITE_KEYWORDS = [
  "school management system",
  "school ERP software",
  "student management system",
  "school ERP India",
  "school administration software",
  "fee management software",
  "attendance management system",
  "exam management software",
  "school timetable software",
  "payroll software for schools",
  "VEDIK",
];

/** Absolute URL for a route path, always with a trailing slash to match `trailingSlash: true`. */
export function siteUrl(path = "/"): string {
  const clean = path === "/" ? "" : path.replace(/\/+$/, "");
  return `${SITE_URL}${clean}/`;
}

/**
 * Social card, served as a real file from /public rather than generated by the
 * `opengraph-image` file convention.
 *
 * A page that exports its own `openGraph` object replaces the inherited one
 * wholesale -- Next.js merges metadata shallowly -- which silently drops the
 * file-convention `images` array. A static path referenced from every page is
 * immune to that, and gives social scrapers a stable, correctly-typed,
 * CDN-cacheable URL instead of a per-build content hash.
 *
 * Regenerate with: python scripts/generate-og-image.py
 */
export const OG_IMAGE = {
  url: "/og-image.png",
  twitterUrl: "/twitter-image.png",
  width: 1200,
  height: 630,
  alt: "VEDIK School ERP — run your entire school from a single dashboard",
};

// ---------------------------------------------------------------------------
// Route registry
// ---------------------------------------------------------------------------

export interface RouteMeta {
  /** Route path without trailing slash. "/" for the landing page. */
  path: string;
  /** Human label used in breadcrumbs and sitemap section grouping. */
  label: string;
  /** Full <title> text, or the part after the root template. */
  title: string;
  /** Meta description. Aim for 140-160 characters. */
  description: string;
  priority: number;
  changeFrequency: "daily" | "weekly" | "monthly" | "yearly";
  /** Parent path for BreadcrumbList, omitted for top-level routes. */
  parent?: string;
  /** Set false to keep a route out of sitemap.xml. */
  inSitemap?: boolean;
}

export const ROUTES = {
  home: {
    path: "/",
    label: "Home",
    title: "School Management ERP Software for Indian Schools",
    description:
      "VEDIK School ERP runs admissions, attendance, exams, fees, payroll, library, transport and hostel management in one dashboard. Explore the live demo of all 18 modules.",
    priority: 1,
    changeFrequency: "weekly",
  },
  login: {
    path: "/login",
    label: "Live Demo",
    title: "Live Demo",
    description:
      "Launch the VEDIK School ERP demo as a principal, teacher or student. No signup and no credentials required - explore all 18 modules instantly.",
    priority: 0.9,
    changeFrequency: "monthly",
  },
  license: {
    path: "/license",
    label: "Pricing",
    title: "Pricing & Plans",
    description:
      "VEDIK School ERP pricing in INR: five plans from a free 14-day trial to Enterprise. Compare module coverage and student limits, then request a personalised quote.",
    priority: 0.9,
    changeFrequency: "monthly",
  },
  dashboard: {
    path: "/dashboard",
    label: "Dashboard",
    title: "Dashboard",
    description:
      "Role-aware overview of your school: attendance, fee collection, enrolment and activity trends, with charts and quick actions for principals, teachers and students.",
    priority: 0.8,
    changeFrequency: "daily",
  },
  academics: {
    path: "/academics",
    label: "Academics",
    title: "Academics",
    description:
      "The academic control centre for your school. Manage classes, sections, subjects and the weekly timetable from one place, with enrolment and class-teacher visibility.",
    priority: 0.8,
    changeFrequency: "monthly",
  },
  classes: {
    path: "/classes",
    label: "Classes",
    title: "Class Management",
    description:
      "Create and manage every class in your school. Track section strength, enrolment totals and the assigned class teacher for each class in a single view.",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  sections: {
    path: "/sections",
    label: "Sections",
    title: "Section Management",
    description:
      "Manage class sections and their student strength. See headcount per section, the responsible class teacher and which sections are active for the current year.",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  subjects: {
    path: "/subjects",
    label: "Subjects",
    title: "Subject Management",
    description:
      "Manage the subject curriculum mapped to classes and teachers. Track subject codes, theory or practical type, and the teacher assigned to each class.",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  timetable: {
    path: "/timetable",
    label: "Timetable",
    title: "Weekly Timetable",
    description:
      "Build and view the weekly class timetable. See period-by-period subject and teacher allocation so substitutions and clashes are visible before they cause disruption.",
    priority: 0.7,
    changeFrequency: "weekly",
  },
  students: {
    path: "/students",
    label: "Students",
    title: "Student Management",
    description:
      "The complete student register. Search and filter by class, section and fee status, edit profiles, and print branded student ID cards in one click.",
    priority: 0.9,
    changeFrequency: "daily",
  },
  teachers: {
    path: "/teachers",
    label: "Teachers",
    title: "Teacher Management",
    description:
      "Teacher profiles with subject specialisation, qualifications, experience and the classes each teacher is assigned to. Open a full profile for detail.",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  staff: {
    path: "/staff",
    label: "Staff",
    title: "Non-Teaching Staff",
    description:
      "Manage non-teaching staff across departments. Track position, department, joining date and employment status for accountants, librarians, drivers and support staff.",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  attendance: {
    path: "/attendance",
    label: "Attendance",
    title: "Attendance Tracking",
    description:
      "Daily attendance for students and staff. Mark present, absent, late or half-day in one grid and get class-wise attendance percentages for any date.",
    priority: 0.9,
    changeFrequency: "daily",
  },
  exams: {
    path: "/exams",
    label: "Examinations",
    title: "Examination Schedule",
    description:
      "Plan and track every examination in the academic year. Manage unit tests, mid-term and final exams with date ranges, applicable classes and live status.",
    priority: 0.8,
    changeFrequency: "monthly",
  },
  marks: {
    path: "/marks",
    label: "Marks & Grades",
    title: "Marks & Grades",
    description:
      "Enter and review student marks against a total, with automatic letter grading. Compare subject performance and spot at-risk students before results are published.",
    priority: 0.8,
    changeFrequency: "monthly",
    parent: "/exams",
  },
  homework: {
    path: "/homework",
    label: "Homework",
    title: "Homework",
    description:
      "Assign homework to a class and section, track submissions and grade them. Teachers see only the assignments relevant to their subject and classes.",
    priority: 0.7,
    changeFrequency: "daily",
  },
  fees: {
    path: "/fees",
    label: "Fees",
    title: "Fee Management",
    description:
      "Track tuition, lab and other fee payments per student. See paid, partial, pending and overdue balances and print branded fee receipts instantly.",
    priority: 0.9,
    changeFrequency: "daily",
  },
  finance: {
    path: "/finance",
    label: "Finance",
    title: "Finance",
    description:
      "School income and expense tracking. Review fee collection against salaries, utilities and equipment spend, with revenue and category charts.",
    priority: 0.7,
    changeFrequency: "monthly",
    parent: "/fees",
  },
  payroll: {
    path: "/payroll",
    label: "Payroll",
    title: "Staff Payroll",
    description:
      "Monthly payroll for teaching and non-teaching staff. Review basic pay, allowances and deductions, then print or download branded payslips.",
    priority: 0.7,
    changeFrequency: "monthly",
    parent: "/fees",
  },
  library: {
    path: "/library",
    label: "Library",
    title: "Library Management",
    description:
      "School library catalogue and circulation. Track total versus available copies by title, ISBN, category and shelf location to spot availability at a glance.",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  transport: {
    path: "/transport",
    label: "Transport",
    title: "Transport",
    description:
      "Manage the school bus fleet. Track vehicles, routes, drivers, seat capacity and how many students are assigned to each route.",
    priority: 0.6,
    changeFrequency: "weekly",
  },
  hostel: {
    path: "/hostel",
    label: "Hostel",
    title: "Hostel",
    description:
      "Manage hostel blocks, warden assignment and room occupancy. See bed capacity against occupied rooms and current occupancy percentage per hostel.",
    priority: 0.6,
    changeFrequency: "weekly",
  },
  inventory: {
    path: "/inventory",
    label: "Inventory",
    title: "Inventory",
    description:
      "Track school inventory across stationery, lab equipment, sports, furniture and medical supplies with low-stock and out-of-stock alerts.",
    priority: 0.6,
    changeFrequency: "weekly",
  },
  communication: {
    path: "/communication",
    label: "Communication",
    title: "Communication",
    description:
      "Send announcements, notices and circulars to students, parents and staff. Set a priority so urgent fee reminders and holidays reach the right audience first.",
    priority: 0.7,
    changeFrequency: "daily",
  },
  certificates: {
    path: "/certificates",
    label: "Certificates",
    title: "Certificates",
    description:
      "Generate and print branded student certificates. Issue bonafide, study, character, transfer and fee certificates with a live preview before printing.",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  leave: {
    path: "/leave",
    label: "Leave",
    title: "Leave Management",
    description:
      "Staff leave requests with an approval workflow. Review sick, casual and earned leave applications, date ranges and reasons, then approve or reject.",
    priority: 0.6,
    changeFrequency: "daily",
  },
  reports: {
    path: "/reports",
    label: "Reports",
    title: "Reports & Analytics",
    description:
      "Analytics for academic, attendance, fee and financial performance. Chart enrolment and collection trends and export the underlying data for further analysis.",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  users: {
    path: "/users",
    label: "Users & Roles",
    title: "Users & Roles",
    description:
      "Manage system users and their roles. Assign principals, teachers, accountants and staff to the modules each role is allowed to reach.",
    priority: 0.5,
    changeFrequency: "monthly",
  },
  settings: {
    path: "/settings",
    label: "Settings",
    title: "Settings",
    description:
      "Configure school profile, academic year, notifications and appearance. School name and branding flow through receipts, certificates and payslips.",
    priority: 0.5,
    changeFrequency: "monthly",
  },
} as const satisfies Record<string, RouteMeta>;

export type RouteKey = keyof typeof ROUTES;

export const ROUTE_KEYS = Object.keys(ROUTES) as RouteKey[];

export function routeMeta(key: RouteKey): RouteMeta {
  return ROUTES[key];
}

/** Breadcrumb trail from the landing page down to `key`, inclusive. */
export function breadcrumbsFor(key: RouteKey): RouteMeta[] {
  const meta = ROUTES[key];
  const trail: RouteMeta[] = [];
  let cursor: RouteMeta | undefined = meta;
  while (cursor) {
    trail.unshift(cursor);
    cursor = cursor.parent ? ROUTES[cursor.parent as RouteKey] : undefined;
  }
  return trail;
}

// ---------------------------------------------------------------------------
// Metadata builder
// ---------------------------------------------------------------------------

/**
 * Build a per-page `Metadata` object from the route registry.
 *
 * Titles intentionally omit the brand suffix here: the root layout supplies a
 * `title.template` so each page renders as "Page Title | VEDIK School ERP".
 * Pages that are already branded (landing, pricing) set `absolute`.
 */
export function buildMetadata(
  key: RouteKey,
  overrides?: Partial<Pick<Metadata, "title" | "description" | "keywords">>,
): Metadata {
  const meta = ROUTES[key];
  const description = meta.description;
  const title =
    typeof overrides?.title === "string"
      ? overrides.title
      : (overrides?.title as { absolute?: string } | undefined)?.absolute ??
        meta.title;

  return {
    title,
    description,
    keywords: overrides?.keywords ?? [...SITE_KEYWORDS],
    alternates: { canonical: siteUrl(meta.path) },
    openGraph: {
      type: "website",
      siteName: SITE.name,
      locale: SITE.locale,
      url: siteUrl(meta.path),
      title,
      description,
      images: [
        {
          url: OG_IMAGE.url,
          width: OG_IMAGE.width,
          height: OG_IMAGE.height,
          alt: OG_IMAGE.alt,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [
        {
          url: OG_IMAGE.twitterUrl,
          width: OG_IMAGE.width,
          height: OG_IMAGE.height,
          alt: OG_IMAGE.alt,
        },
      ],
    },
  };
}

// ---------------------------------------------------------------------------
// Pricing (mirrors src/app/(dashboard)/license)
// ---------------------------------------------------------------------------

export interface Plan {
  name: string;
  tagline: string;
  /** Amounts in INR. null means "not offered on this billing period". */
  prices: { halfYearly: number | null; yearly: number | null; lifetime: number | null };
  modules: number;
  students: number | null;
  popular?: boolean;
  features: string[];
}

export const BILLING_PERIODS = ["halfYearly", "yearly", "lifetime"] as const;
export type BillingPeriod = (typeof BILLING_PERIODS)[number];

export const BILLING_LABELS: Record<BillingPeriod, string> = {
  halfYearly: "Half-Yearly",
  yearly: "Yearly",
  lifetime: "Lifetime",
};

export const PLANS: Plan[] = [
  {
    name: "Trial",
    tagline: "Try VEDIK risk-free",
    prices: { halfYearly: 0, yearly: null, lifetime: null },
    modules: 8,
    students: 50,
    features: [
      "Dashboard",
      "Students",
      "Teachers",
      "Attendance",
      "Fees",
      "Staff",
      "Academics",
      "Settings",
    ],
  },
  {
    name: "Lite",
    tagline: "For small schools",
    prices: { halfYearly: 2999, yearly: 4999, lifetime: 19999 },
    modules: 11,
    students: 200,
    features: [
      "Everything in Trial",
      "Exams",
      "Homework",
      "Reports",
      "Users",
      "License",
    ],
  },
  {
    name: "Essential",
    tagline: "For growing schools",
    prices: { halfYearly: 7999, yearly: 12999, lifetime: 49999 },
    modules: 13,
    students: 1000,
    features: [
      "Everything in Lite",
      "Communication",
      "Certificates",
      "Leave",
      "Timetable",
    ],
  },
  {
    name: "Pro",
    tagline: "Most popular choice",
    prices: { halfYearly: 14999, yearly: 24999, lifetime: 99999 },
    modules: 18,
    students: 5000,
    popular: true,
    features: [
      "Everything in Essential",
      "Finance",
      "Library",
      "Transport",
      "Marks",
      "Sections",
      "Subjects",
    ],
  },
  {
    name: "Enterprise",
    tagline: "For large institutions",
    prices: { halfYearly: 29999, yearly: 49999, lifetime: 199999 },
    modules: 18,
    students: null,
    features: [
      "Everything in Pro",
      "Hostel",
      "Inventory",
      "Multi-School",
      "Priority Support",
      "Custom Branding",
    ],
  },
];

export function formatINR(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

// ---------------------------------------------------------------------------
// Module catalogue (used by the landing page)
// ---------------------------------------------------------------------------

export interface ModuleInfo {
  name: string;
  path: string;
  summary: string;
  group: "Academics" | "People" | "Finance" | "Operations";
}

export const MODULES: ModuleInfo[] = [
  { name: "Dashboard", path: "/dashboard", summary: "Role-aware KPIs, charts and quick actions", group: "Academics" },
  { name: "Students", path: "/students", summary: "Register, profiles and printable ID cards", group: "People" },
  { name: "Teachers", path: "/teachers", summary: "Profiles, subjects and class assignments", group: "People" },
  { name: "Staff", path: "/staff", summary: "Non-teaching staff and departments", group: "People" },
  { name: "Attendance", path: "/attendance", summary: "Daily marking with class-wise percentages", group: "Academics" },
  { name: "Classes", path: "/classes", summary: "Class strength and class teachers", group: "Academics" },
  { name: "Sections", path: "/sections", summary: "Section headcount and ownership", group: "Academics" },
  { name: "Subjects", path: "/subjects", summary: "Curriculum mapped to class and teacher", group: "Academics" },
  { name: "Timetable", path: "/timetable", summary: "Weekly period-by-period allocation", group: "Academics" },
  { name: "Exams", path: "/exams", summary: "Exam windows, scope and status", group: "Academics" },
  { name: "Marks & Grades", path: "/marks", summary: "Marks entry with automatic grading", group: "Academics" },
  { name: "Homework", path: "/homework", summary: "Assignments, submissions and grading", group: "Academics" },
  { name: "Fees", path: "/fees", summary: "Collections, dues and printable receipts", group: "Finance" },
  { name: "Finance", path: "/finance", summary: "Income, expenses and revenue trends", group: "Finance" },
  { name: "Payroll", path: "/payroll", summary: "Staff salary and downloadable payslips", group: "Finance" },
  { name: "Library", path: "/library", summary: "Catalogue, availability and circulation", group: "Operations" },
  { name: "Transport", path: "/transport", summary: "Fleet, routes, drivers and capacity", group: "Operations" },
  { name: "Hostel", path: "/hostel", summary: "Blocks, wardens and bed occupancy", group: "Operations" },
  { name: "Inventory", path: "/inventory", summary: "Stock levels with low-stock alerts", group: "Operations" },
  { name: "Communication", path: "/communication", summary: "Announcements, notices and circulars", group: "People" },
  { name: "Certificates", path: "/certificates", summary: "Branded certificates with live preview", group: "Academics" },
  { name: "Leave", path: "/leave", summary: "Leave requests and approvals", group: "People" },
  { name: "Reports", path: "/reports", summary: "Enrolment, attendance and fee analytics", group: "Finance" },
  { name: "Users & Roles", path: "/users", summary: "Access control by role", group: "People" },
  { name: "Settings", path: "/settings", summary: "School profile, year and appearance", group: "Operations" },
];

// ---------------------------------------------------------------------------
// JSON-LD helpers
// ---------------------------------------------------------------------------

/**
 * Serialise a schema.org graph into a safe inline JSON-LD script body.
 *
 * `<` is escaped to prevent an attacker-controlled string from closing the
 * script tag, per the Next.js JSON-LD guide.
 */
export function jsonLdPayload(data: unknown): string {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}

export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE.organization,
    url: siteUrl("/"),
    logo: siteUrl("/logo.png"),
    email: SITE.contactEmail,
  };
}

export function webSiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE.name,
    alternateName: SITE.shortName,
    url: siteUrl("/"),
    description: SITE.description,
    inLanguage: SITE.lang,
    publisher: { "@id": `${siteUrl("/")}#organization` },
  };
}

export function softwareApplicationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: SITE.name,
    alternateName: `${SITE.shortName} ERP`,
    applicationCategory: SITE.applicationCategory,
    applicationSubCategory: "School Management System",
    operatingSystem: "Web browser",
    url: siteUrl("/"),
    description: SITE.description,
    inLanguage: SITE.lang,
    publisher: { "@id": `${siteUrl("/")}#organization` },
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: SITE.priceCurrency,
      availability: "https://schema.org/InStock",
    },
  };
}

export function breadcrumbSchema(key: RouteKey) {
  const trail = breadcrumbsFor(key);
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.label,
      item: siteUrl(item.path),
    })),
  };
}

export function productSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    name: `${SITE.name} Licence`,
    description: SITE.description,
    brand: { "@type": "Brand", name: SITE.name },
    category: "School Management Software",
    offers: PLANS.filter((plan) => plan.prices.yearly !== null).map((plan) => ({
      "@type": "Offer",
      name: `${plan.name} plan - yearly billing`,
      price: plan.prices.yearly,
      priceCurrency: SITE.priceCurrency,
      availability: "https://schema.org/InStock",
      url: siteUrl("/license"),
      priceValidUntil: "2027-12-31",
    })),
  };
}

export function faqSchema(
  entries: { question: string; answer: string }[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: entries.map((entry) => ({
      "@type": "Question",
      name: entry.question,
      acceptedAnswer: { "@type": "Answer", text: entry.answer },
    })),
  };
}
